### PR TITLE
add catalog

### PR DESCRIPTION
**Pull request by pvpavlov-frontend**
Всем привет

### CODE REVIEW

**Review by derkach2288 — APPROVED** [review]

**Review by VitaliMazurenka — COMMENTED** [review]
add smth

**Comment by pvpavlov-frontend** [comment]
ok

**Review by AGaleeva — CHANGES_REQUESTED** [review]
The file is empty. Please add any content.

**Review by pvpavlov-frontend — COMMENTED** [review]
ok

**Review by pvpavlov-frontend — COMMENTED** [review]
ok

**Review by pvpavlov-frontend — COMMENTED** [review]
ok

**Review by VitaliMazurenka — APPROVED** [review]
красава

**Review by EgorKnestyapin — APPROVED** [review]
Nice!

**Pull request merged**
